-- Migration 009: Tasks table
-- Dedicated task/to-do system with deadline tracking and urgency levels.
-- Linked to clients and cases; can be auto-generated by the Vacuum Protocol.

CREATE TABLE IF NOT EXISTS Tasks (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  title        TEXT NOT NULL,
  description  TEXT,
  status       TEXT NOT NULL DEFAULT 'pending'
               CHECK(status IN ('pending','in_progress','checked','cancelled')),
  priority     TEXT NOT NULL DEFAULT 'normal'
               CHECK(priority IN ('low','normal','high','critical')),
  due_date     TEXT,          -- ISO 8601 datetime (nullable)
  client_id    INTEGER REFERENCES Clients(id) ON DELETE SET NULL,
  case_id      INTEGER REFERENCES Cases(id)   ON DELETE SET NULL,
  document_id  INTEGER REFERENCES Documents(id) ON DELETE SET NULL,
  source       TEXT NOT NULL DEFAULT 'manual'
               CHECK(source IN ('manual','vacuum_protocol','action_plan','system')),
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_tasks_status   ON Tasks(status, due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_client   ON Tasks(client_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON Tasks(due_date) WHERE due_date IS NOT NULL;
